package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

public class ViewAppointmentsController {
	@FXML
	private Button back;
	@FXML
	private Label id;
	@FXML
	private Label name;
	@FXML
	private ListView list;

	// Event Listener on Button[#back].onAction
	@FXML
	public void goToDrDashboard(ActionEvent event) {
		// TODO Autogenerated
	}
}
